name: rh
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.7.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - av==16.1.0
      - baukit==0.0.1
      - beartype==0.14.1
      - beautifulsoup4==4.14.3
      - better-abc==0.0.3
      - bioc==2.1
      - blessed==1.25.0
      - botocore==1.42.25
      - certifi==2026.1.4
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - choreographer==1.2.1
      - circuitsvis==1.43.3
      - click==8.3.1
      - cmake==4.2.1
      - colorama==0.4.6
      - comm==0.2.3
      - conllu==4.5.3
      - dataproperty==1.1.0
      - datasets==3.0.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - deprecated==1.3.1
      - dill==0.3.6
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - einops==0.8.1
      - evaluate==0.4.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fancy-einsum==0.0.3
      - fastapi==0.128.0
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filelock==3.20.3
      - fire==0.7.1
      - flash-attn==2.5.6
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gpustat==1.1.1
      - gradio==5.31.0
      - gradio-client==1.10.1
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - intervaltree==3.2.1
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - jaxtyping==0.3.5
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jsonlines==4.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kaleido==0.2.1
      - langdetect==1.0.9
      - librosa==0.11.0
      - lit==18.1.8
      - llamafactory==0.9.3
      - logistro==2.0.1
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - mizani==0.14.3
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.14
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.2
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - orjson==3.11.5
      - packaging==26.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathvalidate==3.3.1
      - patsy==1.0.2
      - peft==0.15.2
      - pexpect==4.9.0
      - pillow==12.0.0
      - pip==25.3
      - platformdirs==4.5.1
      - plotly==5.19.0
      - plotnine==0.15.2
      - pluggy==1.6.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - pptree==3.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - pytablewriter==1.2.0
      - pytest==9.0.2
      - pytest-timeout==2.4.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyvene==0.1.8
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - responses==0.18.0
      - rich==14.2.0
      - rouge-chinese==1.0.3
      - rouge-score==0.1.2
      - rpds-py==0.30.0
      - ruff==0.14.13
      - sacrebleu==2.4.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - segtok==1.5.11
      - semantic-version==2.10.0
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - setuptools==80.9.0
      - shellingham==1.5.4
      - shtab==1.8.0
      - simplejson==3.20.2
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.8.1
      - soxr==1.0.0
      - sqlitedict==2.1.0
      - sse-starlette==3.2.0
      - stack-data==0.6.3
      - starlette==0.50.0
      - statsmodels==0.14.6
      - sympy==1.14.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - tenacity==9.1.2
      - termcolor==3.3.0
      - tiktoken==0.12.0
      - tokenizers==0.15.2
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.0.1+cu118
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformer-lens==1.17.0
      - transformers==4.37.2
      - transformers-stream-generator==0.0.5
      - triton==2.0.0
      - trl==0.9.6
      - typeguard==4.4.4
      - typepy==1.3.4
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.8.14
      - tzdata==2025.2
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - wadler-lindig==0.1.7
      - wandb==0.23.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - wikipedia-api==0.8.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/Apps/anaconda3/envs/rh
